import express from 'express';
import authRouter from './auth.routes.js';
import userRouter from './user.routes.js';
import adminRouter from './user.routes.js';
import historyRouter from './history.routes.js';
import supportRouter from './support.routes.js';
import auditRouter from './audit.routes.js';
import marketRouter from './market.routes.js';
import notificationRouter from './notification.routes.js';
import walletRouter from './wallet.routes.js';
import binaryRouter from './binary.routes.js';
import p2pRouter from './p2p.routes.js';
import currencyRouter from './currency.routes.js';
import tradingGateRouter from './trading-gate.routes.js';
import transactionRouter from './transaction.route.js';
import pairRouter from './pair.routes.js';

const router = express.Router();
router.use('/auth',          authRouter);
router.use('/user',          userRouter);
router.use('/history',       historyRouter);
router.use('/support',       supportRouter);
router.use('/audit',         auditRouter);
router.use('/market',        marketRouter);
router.use('/admin',         adminRouter);
router.use('/admin',         auditRouter);
router.use('/admin',         currencyRouter);
router.use('/admin',         pairRouter);
router.use('/notifications', notificationRouter);
router.use('/wallet',        walletRouter);
router.use('/binary',        binaryRouter);
router.use('/p2p',           p2pRouter);
router.use('/trading-gate',  tradingGateRouter);
router.use('/admin',         transactionRouter);

export default router;